# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-11 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_qing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='my default location', max_length=120, null=True),
        ),
    ]
